version: "3"

volumes:
  ignore: {}

services:
  server:
    container_name: ruble-ai-backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/usr/src/app/
      - ignore:/usr/src/app/node_modules
